# Generated by Django 5.2 on 2025-11-08 13:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='CC, TI, CE, PP, etc.', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Cédula de Ciudadanía, Tarjeta de Identidad, etc.', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del tipo de documento')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número de documento sin puntos ni espacios', max_length=20, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('telefono', models.CharField(help_text='Número de teléfono con código de país opcional', max_length=15, validators=[django.core.validators.RegexValidator(message="Formato: '+57XXXXXXXXXX' o 'XXXXXXXXXX'", regex='^\\+?57?[0-9]{10,12}$')])),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del cliente')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True)),
                ('direccion', models.TextField(help_text='Dirección completa de residencia')),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Cliente activo en el sistema')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización de datos')),
                ('ultima_compra', models.DateTimeField(blank=True, help_text='Fecha de la última compra realizada', null=True)),
                ('total_compras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total acumulado de todas las compras', max_digits=12)),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de documento de identidad', on_delete=django.db.models.deletion.PROTECT, to='clientes.tipodocumento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Número único de orden de compra', max_length=20, unique=True)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la compra')),
                ('descripcion_productos', models.TextField(help_text='Descripción de los productos comprados')),
                ('cantidad_productos', models.PositiveIntegerField(default=1, help_text='Cantidad total de productos')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal antes de descuentos e impuestos', max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado', max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impuestos (IVA, etc.)', max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de envío', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final de la compra', max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('TRANSFERENCIA', 'Transferencia Bancaria')], help_text='Método de pago utilizado', max_length=20)),
                ('numero_cuotas', models.PositiveIntegerField(default=1, help_text='Número de cuotas (si aplica)')),
                ('canal_venta', models.CharField(choices=[('WEB', 'Página Web'), ('MOVIL', 'Aplicación Móvil'), ('TELEFONO', 'Teléfono'), ('TIENDA', 'Tienda Física'), ('WHATSAPP', 'WhatsApp')], default='WEB', help_text='Canal por el cual se realizó la venta', max_length=20)),
                ('direccion_entrega', models.TextField(help_text='Dirección de entrega de la compra')),
                ('ciudad_entrega', models.CharField(help_text='Ciudad de entrega', max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('DEVUELTA', 'Devuelta')], default='PENDIENTE', help_text='Estado actual de la compra', max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, help_text='Fecha estimada de entrega', null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, help_text='Fecha real de entrega', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la compra')),
                ('codigo_seguimiento', models.CharField(blank=True, help_text='Código de seguimiento del envío', max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('usuario_creacion', models.CharField(blank=True, help_text='Usuario que registró la compra', max_length=100)),
                ('cliente', models.ForeignKey(help_text='Cliente que realizó la compra', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_compra'],
                'indexes': [models.Index(fields=['numero_orden'], name='clientes_co_numero__d6f8ba_idx'), models.Index(fields=['cliente', '-fecha_compra'], name='clientes_co_cliente_4591bb_idx'), models.Index(fields=['estado'], name='clientes_co_estado_9a869b_idx'), models.Index(fields=['fecha_compra'], name='clientes_co_fecha_c_73a751_idx'), models.Index(fields=['metodo_pago'], name='clientes_co_metodo__fa088f_idx'), models.Index(fields=['canal_venta'], name='clientes_co_canal_v_1d1aa0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_documento'], name='clientes_cl_numero__868cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['correo'], name='clientes_cl_correo_38c1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['fecha_registro'], name='clientes_cl_fecha_r_6e4746_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='clientes_cl_activo_b76065_idx'),
        ),
    ]
